# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Maxwell Fishman
title: Data Engineer
email: fishman.maxwell@gmail.com
website: mfishman26.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
# github_username:  mfishman26
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: maxwellfishman
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Maxwell Fishman and I am a data engineer at II-VI Inc., Advanced Materials Division. My primary fields of intersest are machine learning, condensed matter physics, and quantum computation. In particular, I am fascinated by the application of machine learning algorithms to condensed matter research.

content:
  # - title: Publications # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Field-Tunable Topological Phase Transitions and Spin-Hall Effects in 2D Crystals
  #       link: https://arxiv.org/abs/2012.09668
  #       link_text: M. Fishman, D. Jena, arXiv:2012.09688

  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - M. Fishman, D. Jena, "Field-Tunable Topological Phase Transitions and Spin-Hall Effects in 2D Crystals", [arXiv:2012.09688 (2020)](https://arxiv.org/abs/2012.09668)
      - M.S. Thesis: M. Fishman, D. Jena, "Ballistic Transport and Large Spin Hall Effect in a Silicene MOSFET", [ecommons.cornell.edu/handle/1813/47763 (2017)](https://ecommons.cornell.edu/handle/1813/47763)

  - title: Education
    layout: text
    content: |
      - **Cornell University**, Ithaca, NY, January 2017 \
        M.S. Applied Physics, **GPA: 3.69**

      - **Rutgers University**, Piscataway, NJ, May 2012 \
        B.S. Mechanical Engineering, **GPA: 3.64**

  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: II-VI Inc.
        link: https://ii-vi.com/silicon-carbide-substrates-capabilities/
        # link_text: boringcompany.com
        sub_title: Data Engineer
        caption: December 2017 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Develop data analytics pipelines for tracking and analyzing SiC substrate R&D and production.
          - Statistical process control development using python, C#, and VBA.
          - Developed SECS/GEM software for monitoring tool states.
          - Managed SQL Server databases for all production lines.
          - Utilized Keras on top of Tensorflow to develop semiconductor defect detection computer vision software using convolutional neural networks.
      - layout: left
        title: Rudewell LLC
        # link: https://ii-vi.com/silicon-carbide-substrates-capabilities/
        # link_text: boringcompany.com
        sub_title: Co-owner & Software Engineer
        caption: Jan. 2017 - Jan. 2020
        description: | # this will include new lines to allow paragraphs
          - Designed and implemented real-time applications using the Godot engine.
          - Worked in a team of three to successfully develop and deploy applications targeted for iOS and Android.
          - Responsibilities included: 
            - project planning
            - Timeline management
            - Application prototyping and development
      - layout: left
        title: Cornell University
        link: https://www.cornell.edu/
        sub_title: Research Assistant
        caption: May 2015 - Aug. 2015
        description: | # this will include new lines to allow paragraphs
          - Summer research assistant in Professor Debdeep Jena’s (Electrical and Computer Engineering department) group as a precursor to my graduate thesis.
          - Computationally modeled electronic properties of 2D materials such as silicene, graphene, and transition metal dichalcogenides.
          - Researched ballistic transistor modeling methods with primary focus on the Landauer approach originally employed by Kenji Natori. Discovered how to employ these methods using 2D materials.
      - layout: left
        title: Structured Materials Industries Inc.
        link: https://www.smicvd.com/
        sub_title: Mechanical Engineer
        caption: Oct. 2017 - April 2013
        description: | # this will include new lines to allow paragraphs
          - Designed and built semiconductor and related low-pressure thin film chemical vapor deposition (CVD) equipment.
          - Responsibilities included: 
            - Component design using SolidWorks and AutoCAD
            - Overseeing component installation
            - Checking component operation
            - Updating CVD system schematics to include new components and layouts
            - Writing manuals for system assembly/disassembly

  # - title: Education # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Cornell University
  #       caption: 2014 - 2016
  #       sub_title: "M.S. Applied Physics, GPA: 3.69"
  #     - layout: top-middle
  #       title: Rutgers University
  #       caption: 2010 - 2012
  #       sub_title: "B.S. Mechanical Engineering, GPA: 3.64"

  # - title: Education # Title for the section
  #     layout: text # Type of content section (list/text)
  #     content: |
  #       # - layout: left
  #       #   title: Cornell University
  #       #   caption: 2014 - 2016
  #       #   sub_title: M.S. Applied Physics

  - title: Research Experience
    layout: list
    content:
      - layout: left
        title: Silicene Field Effect Transistor Transport Properties
        link: https://hdl.handle.net/1813/47763
        # link_text: boringcompany.com
        sub_title: Under Dr. Debdeep Jena
        caption: Cornell University, Jun. 2015 – Dec. 2016
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Researched transport properties of silicene (monolayer silicon) and how the topologically non-trivial nature of silicene affects transport under perpendicular and transverse electric fields of varying strengths.
          - Developed a computational current model for a silicene-channel independent double gate ballistic field effect transistor.
            - Successfully modeled the source-drain current as well as transverse Hall currents.
            - Discovered a unique transverse spin current that arises under a symmetric gate voltages due to silicene’s unique electronic properties.
          - Wrote a thesis on model development and findings.
      - layout: left
        title: Transparent Luminescent Solar Concentrators
        sub_title: Under Dr. David Muller
        caption: Cornell University, Mar. 2015 - May 2015
        description: |
          - Investigated the recent advances of transparent luminescent solar concentrator technology for use in transparent solar cells and the viability of implementing this technology on a large scale.
          - Presented findings at a university held poster session.
      - layout: left
        title: AFM Nanolithography
        sub_title: Under Dr. Gregory Fuchs
        caption: Cornell University, Mar. 2015 - May 2015
        description: |
          - Investigated the viability of force based AFM nanolithography as a patterning method compared to its competitors, such as photolithography and electron-beam lithography.
          - Presented findings at a university held poster session.
      - layout: left
        title: Atomic Spin Detection with MRFM
        sub_title: Under Dr. Lena Kourkoutis
        caption: Cornell University, Oct. 2014 - Dec. 2014
        description: |
          - Investigated the current state of magnetic resonance force microscopy and in particular its capabilities concerning single spin detection.
          - Used these results to quantitatively compare this characterization method to cryo-electron microscopy.
      - layout: left
        title: Personal Energy Harvesting Sensory system
        sub_title: Under Dr. Jerry Shan
        caption: Rutgers University, Sept. 2011 - May 2012
        description: |
          - Led a team of 3 colleagues to develop a solar, heat, and kinetic energy harvesting sensory system.
            - Used solid state thermoelectric generators and a thin film piezoelectric oscillator.
            - Worn by the user, the system measures calories expended, steps taken, and core body temperature.
          - Sensory data is computed and wirelessly sent from the system to a computer for analysis.
          - Data is graphically displayed and updated in real-time through a graphical user interface.
          - Responsibilities included: o Budgettracking
            - Researching thermoelectric generators
            - Developing the wireless data sensory circuits and programs 
            - Developing the graphical user interface
      - layout: left
        title: Computational Vehicle Roll Center Analysis
        sub_title: Under Dr. Haim Baruh
        caption: Rutgers University, Jan. 2012 - May 2012
        description: |
          - Researched vehicle roll characteristics and how they change due to alterations in suspension geometry and wheel displacement.
          - Developed a vehicle simulation program, which models vehicle roll center location throughout a range of wheel displacements for any suspension geometry.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
