# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Maxwell Fishman
title: Data Engineer
email: fishman.maxwell@gmail.com
website: mfishman26.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
# github_username:  mfishman26
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: maxwellfishman
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Maxwell Fishman and I am a data engineer at II-VI Inc., Advanced Materials Division.

content:
  # - title: Publications # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Field-Tunable Topological Phase Transitions and Spin-Hall Effects in 2D Crystals
  #       link: https://arxiv.org/abs/2012.09668
  #       link_text: M. Fishman, D. Jena, arXiv:2012.09688

  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - M. Fishman, D. Jena, "Field-Tunable Topological Phase Transitions and Spin-Hall Effects in 2D Crystals", [arXiv:2012.09688 (2020)](https://arxiv.org/abs/2012.09668)
      - M.S. Thesis: M. Fishman, D. Jena, "Ballistic Transport and Large Spin Hall Effect in a Silicene MOSFET", [ecommons.cornell.edu/handle/1813/47763 (2017)](https://ecommons.cornell.edu/handle/1813/47763)

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: II-VI Inc.
        link: https://ii-vi.com/silicon-carbide-substrates-capabilities/
        # link_text: boringcompany.com
        sub_title: Data Engineer
        caption: December 2017 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Develop data analytics pipelines for tracking and analyzing SiC substrate R&D and production.
          - Statistical process control development using python, C#, and VBA.
          - Developed SECS/GEM software for monitoring tool states.
          - Managed SQL Server databases for all production lines.
          - Utilized Keras on top of Tensorflow to develop semiconductor defect detection computer vision software using convolutional neural networks.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Cornell University
        caption: 2014 - 2016
        sub_title: "M.S. Applied Physics, GPA: 3.69"
      - layout: top-middle
        title: Rutgers University
        caption: 2010 - 2012
        sub_title: "B.S. Mechanical Engineering, GPA: 3.64"

  # - title: Education # Title for the section
  #     layout: text # Type of content section (list/text)
  #     content: |
  #       # - layout: left
  #       #   title: Cornell University
  #       #   caption: 2014 - 2016
  #       #   sub_title: M.S. Applied Physics

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
